language: node_js
sudo: false
node_js:
- 4
- 6
- stable
script:
- tsc # use the tsconfig.json to transpile specified service-files
- mocha test/unit/test.language_translator.v2.js test/integration/test.language_translator.js
- mocha test/unit/test.discovery.v1.js test/integration/test.discovery.js
- mocha test/unit/test.natural_language_classifier.v1.js
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_cb4d3d070e32_key
  -iv $encrypted_cb4d3d070e32_iv -in auth.js.enc -out test/resources/auth.js -d ||
  true'
- npm install -g typescript